<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>disable</Nullable>
    <Deterministic>False</Deterministic>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <Configurations>Debug;Release</Configurations>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Copyright>Copyright (c) 2026 DVMProject (https://github.com/dvmproject) Authors.</Copyright>
    <PlatformTarget>x86</PlatformTarget>
    <PackageLicenseExpression>MIT-only</PackageLicenseExpression>
    <ApplicationIcon>kfdtool-icon.ico</ApplicationIcon>
    <Title>KFD EKC Editor/Keyloader</Title>
    <Authors>DVMProject (https://github.com/dvmproject) Authors</Authors>
    <Company>DVMProject</Company>
    <Product>KFD EKC Editor/Keyloader</Product>
    <PackageProjectUrl>https://github.com/DVMProject/kfdekc</PackageProjectUrl>
    <PackageIcon>AppIcon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/DVMProject/kfdekc</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
    <FileVersion>1.2.0.0</FileVersion>
    <AssemblyInformationalVersion>R01A00 ($(SourceRevisionId))</AssemblyInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\Algos\AES.png" />
    <None Remove="Images\Algos\ARC4.png" />
    <None Remove="Images\Algos\DES.png" />
    <None Remove="Images\Algos\OTHER.png" />
    <None Remove="Images\kfdtool-icon.ico" />
    <None Remove="Images\kfdtool-icon.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\fnecore\fnecore.csproj" />
    <ProjectReference Include="..\Keyloader\KFDtool.Adapter\KFDtool.Adapter.csproj" />
    <ProjectReference Include="..\Keyloader\KFDtool.P25\KFDtool.P25.csproj" />
    <ProjectReference Include="..\KFDEKC.Container\KFDEKC.Container.csproj" />
    <ProjectReference Include="..\KFDEKC.Shared\KFDEKC.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Algos\AES.png" />
    <Resource Include="Images\Algos\ARC4.png" />
    <Resource Include="Images\Algos\DES.png" />
    <Resource Include="Images\Algos\OTHER.png" />
    <Resource Include="Images\kfdtool-icon.ico" />
    <Resource Include="Images\kfdtool-icon.png" />
  </ItemGroup>
</Project>
